<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-CHDTIFA" failures="4" tests="33" name="SIP.Call_Dispostion" time="176.047" errors="0" timestamp="2025-03-19T09:44:08 IST" skipped="0">
  <testcase classname="SIP.Call_Dispostion" name="Dealer_User_Login1" time="6.259"/>
  <system-out/>
  <testcase classname="SIP.Call_Dispostion" name="Click_On_SIP" time="5.791"/>
  <system-out/>
  <testcase classname="SIP.Call_Dispostion" name="Click_On_Additional_Fillter_To_Clear_Data" time="5.530"/>
  <system-out/>
  <testcase classname="SIP.Call_Dispostion" name="Click_On_Customer_Page" time="3.453"/>
  <system-out/>
  <testcase classname="SIP.Call_Dispostion" name="Click_On_Call_Dispostion" time="0.194"/>
  <system-out/>
  <testcase classname="SIP.Call_Dispostion" name="Verify_Booking_Feedback" time="5.962"/>
  <system-out/>
  <testcase classname="SIP.Call_Dispostion" name="Booking_Feedback_SuccessMessage" time="0.066"/>
  <system-out/>
  <testcase classname="SIP.Call_Dispostion" name="Click_On_Customer1" time="8.373"/>
  <system-out/>
  <testcase classname="SIP.Call_Dispostion" name="Verify_Call_Me_Later" time="6.453"/>
  <system-out/>
  <testcase classname="SIP.Call_Dispostion" name="Call_Me_Later_SuccessMessage" time="0.326"/>
  <system-out/>
  <testcase classname="SIP.Call_Dispostion" name="Click_On_Customer2" time="8.229"/>
  <system-out/>
  <testcase classname="SIP.Call_Dispostion" name="Verify_WrongNumber" time="2.111"/>
  <system-out/>
  <testcase classname="SIP.Call_Dispostion" name="WrongNumber_SuccessMessage" time="0.308"/>
  <system-out/>
  <testcase classname="SIP.Call_Dispostion" name="Click_On_Customer3" time="8.245"/>
  <system-out/>
  <testcase classname="SIP.Call_Dispostion" name="Verify_VehicleDelivery_Visit" time="5.777"/>
  <system-out/>
  <testcase classname="SIP.Call_Dispostion" name="VehicleDelivery_Visit_SuccessMessage" time="0.282"/>
  <system-out/>
  <testcase classname="SIP.Call_Dispostion" name="Click_On_Customer4" time="8.252"/>
  <system-out/>
  <testcase classname="SIP.Call_Dispostion" name="ClickOn_NotPickedUp" time="1.899"/>
  <system-out/>
  <testcase classname="SIP.Call_Dispostion" name="Verify_NotPickedUp" time="4.315"/>
  <system-out/>
  <testcase classname="SIP.Call_Dispostion" name="NotPickedUp_SuccessMessage" time="10.628">
    <failure message="After Punching NotPickedUp success message is not Display " type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: After Punching NotPickedUp success message is not Display 
at org.testng.Assert.fail(Assert.java:99)
at SIP.Call_Dispostion.NotPickedUp_SuccessMessage(Call_Dispostion.java:192)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- NotPickedUp_SuccessMessage -->
  <system-out/>
  <testcase classname="SIP.Call_Dispostion" name="Click_On_Customer5" time="8.253"/>
  <system-out/>
  <testcase classname="SIP.Call_Dispostion" name="ClickOn_NumberBusy" time="1.929"/>
  <system-out/>
  <testcase classname="SIP.Call_Dispostion" name="Verify_NumberBusy" time="4.299"/>
  <system-out/>
  <testcase classname="SIP.Call_Dispostion" name="NumberBusy_SuccessMessage" time="10.563">
    <failure message="After Punching NumberBusy success message is not Display " type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: After Punching NumberBusy success message is not Display 
at org.testng.Assert.fail(Assert.java:99)
at SIP.Call_Dispostion.NumberBusy_SuccessMessage(Call_Dispostion.java:219)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- NumberBusy_SuccessMessage -->
  <system-out/>
  <testcase classname="SIP.Call_Dispostion" name="Click_On_Customer6" time="8.377"/>
  <system-out/>
  <testcase classname="SIP.Call_Dispostion" name="ClickOn_NotRechable" time="1.951"/>
  <system-out/>
  <testcase classname="SIP.Call_Dispostion" name="Verify_NotRechable" time="4.362"/>
  <system-out/>
  <testcase classname="SIP.Call_Dispostion" name="NotRechable_SuccessMessage" time="10.586">
    <failure message="After Punching NotRechable success message is not Display " type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: After Punching NotRechable success message is not Display 
at org.testng.Assert.fail(Assert.java:99)
at SIP.Call_Dispostion.NotRechable_SuccessMessage(Call_Dispostion.java:246)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- NotRechable_SuccessMessage -->
  <system-out/>
  <testcase classname="SIP.Call_Dispostion" name="Click_On_Customer7" time="8.262"/>
  <system-out/>
  <testcase classname="SIP.Call_Dispostion" name="ClickOn_SwitchedOff" time="1.921"/>
  <system-out/>
  <testcase classname="SIP.Call_Dispostion" name="Verify_SwitchedOff" time="4.280"/>
  <system-out/>
  <testcase classname="SIP.Call_Dispostion" name="SwitchedOff_SuccessMessage" time="10.610">
    <failure message="After Punching SwitchedOff success message is not Display " type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: After Punching SwitchedOff success message is not Display 
at org.testng.Assert.fail(Assert.java:99)
at SIP.Call_Dispostion.SwitchedOff_SuccessMessage(Call_Dispostion.java:273)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- SwitchedOff_SuccessMessage -->
  <system-out/>
  <testcase classname="SIP.Call_Dispostion" name="Click_On_Customer8" time="8.201"/>
  <system-out/>
</testsuite> <!-- SIP.Call_Dispostion -->
